remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 6
description: In this lab we work on gaining more experience with classes. We also prepare for next lab by creating a GitHub account. 
